on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
name: "Build & Release"
jobs:
  build_android:
    name: Build Android & Release
    runs-on: macos-latest
    env: 
      KEY_JKS: ${{ secrets.KEY_JKS }}
      KEY_PATH: "key.jks"
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.19.2"
      - run: flutter pub get
      - run: flutter build apk --release --no-shrink --verbose
      - run: flutter build appbundle --verbose
      - name: Push Android Artifacts to Releases   
        uses: ncipollo/release-action@v1  
        with:
          artifacts: "build/app/outputs/flutter-apk/*,build/app/outputs/bundle/release/*"
          tag: v1.0.${{github.run_number}} 
          token: ${{secrets.DEMOTOKEN}}
      - name: Upload app bundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab    
  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '15.2' 
      - name: Build iOS App
        run: flutter build ios --release --no-codesign
        
  distribute:
    name: Distribute using Firebase App Distribution
    runs-on: macos-latest
    needs: [build_android, build_ios]
    steps:
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      - name: Firebase login
        run: firebase login:ci --no-localhost
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Upload APK to Firebase App Distribution
        run: firebase appdistribution:distribute build/app/outputs/flutter-apk/*.apk --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Upload iOS Build to Firebase App Distribution
        run: firebase appdistribution:distribute build/ios/Runner.ipa --token "${{ secrets.FIREBASE_TOKEN }}"
